// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// AHD
Rcpp::List AHD(const Rcpp::NumericMatrix& Dx, const Rcpp::NumericMatrix& Dy);
RcppExport SEXP _AHD_AHD(SEXP DxSEXP, SEXP DySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type Dy(DySEXP);
    rcpp_result_gen = Rcpp::wrap(AHD(Dx, Dy));
    return rcpp_result_gen;
END_RCPP
}
// AHD_test
List AHD_test(const NumericMatrix& Dx, const NumericMatrix& Dy, const IntegerMatrix& perms);
RcppExport SEXP _AHD_AHD_test(SEXP DxSEXP, SEXP DySEXP, SEXP permsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Dx(DxSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type Dy(DySEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type perms(permsSEXP);
    rcpp_result_gen = Rcpp::wrap(AHD_test(Dx, Dy, perms));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_AHD_AHD", (DL_FUNC) &_AHD_AHD, 2},
    {"_AHD_AHD_test", (DL_FUNC) &_AHD_AHD_test, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_AHD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
