# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

AHD <- function(Dx, Dy) {
    .Call(`_AHD_AHD`, Dx, Dy)
}

AHD_test <- function(Dx, Dy, perms) {
    .Call(`_AHD_AHD_test`, Dx, Dy, perms)
}

